[package]
name = "tagparser_r"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.6.0"
toml = "0.5.9"
walkdir = "2"

[[bin]]
name = "tagparser_r"
path = "main.rs"
