baseURL = "http://localhost:1313"
languageCode = "en-us"
title = "Of Chaos and Order"
author = "Alex Bilson"
theme = "chaos"
sectionPagesMenu = "main"
defaultColorMode = "light"

[params]
	PublishUri = "http://localhost:3000"
	AuthenticationUri = "http://localhost:3000"

[taxonomies]
  author = "authors"
  tag = "tags"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
